### ISSUE TITLE
TypeError: Object.keys called on non-object

### ISSUE THREAD

**Issue by binarykitchen** [es-shims/es5-shim#387]
Using your latest version on npm.

Here the stack trace:

```
/home/travis/build/binarykitchen/videomail-client/node_modules/es5-shim/es5-shim.js:1074

            return originalKeys(object);

                   ^

TypeError: Object.keys called on non-object

    at keys (native)

    at Function.keys (/home/travis/build/binarykitchen/videomail-client/node_modules/es5-shim/es5-shim.js:1074:20)

    at stringify (/home/travis/build/binarykitchen/videomail-client/src/util/videomailError.js:19:28)

    at Function.VideomailError.create (/home/travis/build/binarykitchen/videomail-client/src/util/videomailError.js:167:35)

    at Test.<anonymous> (/home/travis/build/binarykitchen/videomail-client/test/util/videomailError.test.js:92:38)

    at Test.bound [as _cb] (/home/travis/build/binarykitchen/videomail-client/node_modules/tape/lib/test.js:61:32)

    at Test.run (/home/travis/build/binarykitchen/videomail-client/node_modules/tape/lib/test.js:77:10)

    at Test.bound [as run] (/home/travis/build/binarykitchen/videomail-client/node_modules/tape/lib/test.js:61:32)

    at Test._end (/home/travis/build/binarykitchen/videomail-client/node_modules/tape/lib/test.js:143:11)

    at Test.bound [as _end] (/home/travis/build/binarykitchen/videomail-client/node_modules/tape/lib/test.js:61:32)
```

**Comment by ljharb** [comment]
`Object.keys` only accepts an object in ES5 - perhaps something in the stack trace is passing a string? I do see a `stringify` function.

If you also apply the `es6-shim`, `Object.keys` works on primitives as of ES6.

**Comment by binarykitchen** [comment]
ah, with the es6-shim it worked. thx
